PRODUCTION_TEST_CASES = [
    # Format : (question, expected_intent_label, expected_intent_id)

    # GREETING
    ("Bonjour", "GREETING", 1),
    ("Salut comment allez-vous", "GREETING", 1),
    ("Bonsoir j'espère que vous allez bien", "GREETING", 1),
    ("Bjr madame désolé du dérangement", "GREETING", 1),
    ("Hey j'espère que tout va bien de votre côté", "GREETING", 1),
    ("Yo c'est comment là", "GREETING", 1),
    ("Bonjour pardon de vous déranger à cette heure", "GREETING", 1),
    ("Salut j'espère la famille va bien", "GREETING", 1),
    ("Bondjour coment sa va", "GREETING", 1),
    ("Merci beaucoup pour votre aide", "GREETING", 1),

    # INFO_GENERAL
    ("Vous êtes situés où exactement", "INFO_GENERAL", 2),
    ("C'est quoi votre adresse svp", "INFO_GENERAL", 2),
    ("Vous ouvrez à quelle heure le matin", "INFO_GENERAL", 2),
    ("Vous êtes ouvert le dimanche", "INFO_GENERAL", 2),
    ("Comment je peux vous joindre", "CONTACT_COORDONNEES", 13),
    ("Quel est votre numéro WhatsApp", "CONTACT_COORDONNEES", 13),
    ("Vous êtes à quel quartier d'Abidjan", "INFO_GENERAL", 2),
    ("Jusqu'à quelle heure vous fermez", "INFO_GENERAL", 2),
    ("Depuis quand vous existez", "INFO_GENERAL", 2),
    ("C'est où votre boutique exactement", "INFO_GENERAL", 2),

    # CONTACT_COORDONNEES
    ("Mon numéro c'est 0707070707", "CONTACT_COORDONNEES", 13),
    ("Je suis joignable sur WhatsApp au 0505050505", "CONTACT_COORDONNEES", 13),
    ("Voici mes coordonnées : +225 07 87 36 07 57", "CONTACT_COORDONNEES", 13),
    ("Appelez-moi sur ce numéro : 07 07 07 07 07", "CONTACT_COORDONNEES", 13),
    ("Tu peux me joindre au 01 02 03 04 05", "CONTACT_COORDONNEES", 13),
    ("Mon contact WhatsApp : +225 07 87 36 07 57", "CONTACT_COORDONNEES", 13),

    # PRODUCT_INFO
    ("Vous avez quel type de produits", "PRODUCT_INFO", 4),
    ("C'est quoi les caractéristiques", "PRODUCT_INFO", 5),
    ("Il y a combien de modèles disponibles", "PRODUCT_INFO", 4),
    ("Vous vendez quelle marque", "PRODUCT_INFO", 5),
    ("Quelle est la taille exacte", "PRODUCT_INFO", 5),
    ("C'est disponible en quelle couleur", "PRODUCT_INFO", 5),
    ("Le produit fait combien de grammes", "PRODUCT_INFO", 5),
    ("C'est pour quel âge ce produit", "PRODUCT_INFO", 5),
    ("Vous avez la référence du produit", "PRODUCT_INFO", 5),
    ("C'est fabriqué où", "PRODUCT_INFO", 5),
    ("La composition c'est quoi", "PRODUCT_INFO", 5),
    ("Il y a une garantie avec", "PRODUCT_INFO", 5),

    # PRICE
    ("C'est combien", "PRICE", 6),
    ("Quel est le prix svp", "PRICE", 6),
    ("Ça coûte combien exactement", "PRICE", 6),
    ("Le tarif c'est combien", "PRICE", 6),
    ("Vous faites combien pour ce produit", "PRICE", 6),
    ("C'est à combien le paquet", "PRICE", 6),
    ("Le prix unitaire c'est quoi", "PRICE", 6),
    ("Vous avez des promotions en ce moment", "PRICE", 6),
    ("Il y a une réduction si j'achète beaucoup", "PRICE", 6),
    ("C'est en solde actuellement", "PRICE", 6),
    ("Vous faites des remises", "PRICE", 6),
    ("Combien je vais payer au total", "PRICE", 6),
    ("Le prix a augmenté ou pas", "PRICE", 6),
    ("C'est le même prix partout", "PRICE", 6),
    ("Vous avez un prix gros", "PRICE", 6),

    # STOCK
    ("C'est disponible maintenant", "STOCK", 7),
    ("Vous avez en stock", "STOCK", 7),
    ("Il en reste combien", "STOCK", 7),
    ("C'est dispo pour aujourd'hui", "STOCK", 7),
    ("Vous avez le produit X en stock", "STOCK", 7),
    ("C'est en rupture ou pas", "STOCK", 7),
    ("Vous n'avez plus ce modèle", "STOCK", 7),
    ("Quand ça revient en stock", "STOCK", 7),
    ("Il reste des paquets", "STOCK", 7),
    ("Vous avez combien de pièces disponibles", "STOCK", 7),

    # ORDER_CREATE
    ("Je veux commander", "ORDER_CREATE", 8),
    ("Je voudrais acheter 5 paquets", "ORDER_CREATE", 8),
    ("Comment je fais pour passer commande", "ORDER_CREATE", 8),
    ("Je prends 3 unités", "ORDER_CREATE", 8),
    ("Mets-moi 2 paquets svp", "ORDER_CREATE", 8),
    ("Je veux acheter ce produit", "ORDER_CREATE", 8),
    ("Envoie-moi 10 pièces", "ORDER_CREATE", 8),
    ("Je commande pour demain", "ORDER_CREATE", 8),
    ("Garde-moi 4 paquets", "ORDER_CREATE", 8),
    ("Je réserve 2 articles", "ORDER_CREATE", 8),
    ("Comment passer ma commande", "ORDER_CREATE", 8),
    ("Je souhaite commander maintenant", "ORDER_CREATE", 8),

    # ORDER_MODIFY
    ("Je veux modifier ma commande", "ORDER_MODIFY", 11),
    ("Je veux annuler ma commande svp", "ORDER_MODIFY", 11),
    ("Changer la quantité de ma commande", "ORDER_MODIFY", 11),
    ("Ajouter 2 paquets à ma commande", "ORDER_MODIFY", 11),
    ("Enlever un article de la commande", "ORDER_MODIFY", 11),
    ("Je ne veux plus la commande", "ORDER_MODIFY", 11),
    ("Supprimer ma commande d'hier", "ORDER_MODIFY", 11),
    ("Modifier ce que j'ai commandé hier", "ORDER_MODIFY", 11),

    # PAYMENT
    ("Comment je paye", "PAYMENT", 10),
    ("Quel est le mode de paiement", "PAYMENT", 10),
    ("Vous acceptez Mobile Money", "PAYMENT", 10),
    ("Je peux payer en espèces", "PAYMENT", 10),
    ("Vous prenez Orange Money", "PAYMENT", 10),
    ("Paiement à la livraison c'est possible", "PAYMENT", 10),
    ("Je veux une facture", "PAYMENT", 10),
    ("Vous acceptez MTN Money", "PAYMENT", 10),

    # DELIVERY_INFO
    ("Vous livrez où", "DELIVERY_INFO", 9),
    ("Vous livrez à Yopougon", "DELIVERY_INFO", 9),
    ("La livraison prend combien de temps", "DELIVERY_INFO", 9),
    ("Ça arrive quand la livraison", "DELIVERY_INFO", 9),
    ("Les frais de livraison c'est combien", "DELIVERY_INFO", 9),
    ("La livraison est gratuite", "DELIVERY_INFO", 9),
    ("Vous livrez dans quel quartier", "DELIVERY_INFO", 9),
    ("Combien pour livrer à Cocody", "DELIVERY_INFO", 9),
    ("Vous livrez le weekend", "DELIVERY_INFO", 9),
    ("Quelles zones vous couvrez", "DELIVERY_INFO", 9),

    # DELIVERY_MODIFY
    ("Je veux changer l'adresse de livraison", "DELIVERY_MODIFY", 11),
    ("Modifier l'adresse svp", "DELIVERY_MODIFY", 11),
    ("Reporter la livraison à demain", "DELIVERY_MODIFY", 11),
    ("Changer la date de livraison", "DELIVERY_MODIFY", 11),
    ("Livrer à une autre adresse", "DELIVERY_MODIFY", 11),

    # TRACKING
    ("Où est mon colis", "TRACKING", 11),
    ("Quand arrive ma commande", "TRACKING", 11),
    ("Le livreur est où exactement", "TRACKING", 11),
    ("J'ai pas encore reçu ma commande", "TRACKING", 11),
    ("Quel est le statut de ma livraison", "TRACKING", 11),
    ("Ma commande a été expédiée", "TRACKING", 11),
    ("C'est en cours de livraison", "TRACKING", 11),
    ("Toujours pas livré", "TRACKING", 11),
    ("Le suivi de ma commande svp", "TRACKING", 11),
    ("Ça n'est pas arrivé", "TRACKING", 11),

    # CAS COMPLEXES (Salut + question)
    ("Salut j'espère que vous allez bien, c'est combien le paquet", "PRICE", 6),
    ("Bonjour madame désolé du dérangement, vous livrez à Abobo", "DELIVERY_INFO", 9),
    ("Bjr comment tu vas, c'est disponible en stock", "STOCK", 7),
    ("Hey j'espère que tout va bien, je veux commander 5 paquets", "ORDER_CREATE", 8),
    ("Yo la forme, où est mon colis svp", "TRACKING", 11),
    ("Bonjour pardon de te déranger, vous acceptez Mobile Money", "PAYMENT", 10),
    ("Salut ça dit quoi, quand ça arrive ma commande", "TRACKING", 11),
    ("Bjr chef, je veux modifier ma commande d'hier", "ORDER_MODIFY", 11),
    ("Bonjour j'espère la famille va bien, vous êtes situés où exactement", "INFO_GENERAL", 2),
    ("Salut pardon oh, les frais de livraison c'est combien", "DELIVERY_INFO", 9),
]
