PRODUCTION_TEST_CASES = [
    # Format : (question, expected_intent_label, expected_intent_id)

    # GREETING
    ("Bonjour", "GREETING", 1),
    ("Salut", "GREETING", 1),
    ("Bjr", "GREETING", 1),
    ("Bonsoir", "GREETING", 1),
    ("Hey", "GREETING", 1),
    ("Cc", "GREETING", 1),
    ("Yo", "GREETING", 1),
    ("Hello", "GREETING", 1),
    ("Salut ça va", "GREETING", 1),
    ("Bonjour ici", "GREETING", 1),
    ("Merci beaucoup", "GREETING", 1),
    ("Ok merci", "GREETING", 1),
    ("D'accord merci", "GREETING", 1),
    ("C'est gentil", "GREETING", 1),
    ("Merci bien", "GREETING", 1),

    # INFO_GENERAL
    ("Où vous trouvez-vous", "INFO_GENERAL", 2),
    ("Vous êtes situé où", "INFO_GENERAL", 2),
    ("Vous êtes dans quel quartier", "INFO_GENERAL", 2),
    ("C'est où votre boutique", "INFO_GENERAL", 2),
    ("Quelle est votre adresse", "INFO_GENERAL", 2),
    ("Vous êtes à Abidjan", "INFO_GENERAL", 2),
    ("Vous livrez dans quelle zone", "DELIVERY_INFO", 9),
    ("Vous êtes situé où exactement", "INFO_GENERAL", 2),
    ("Je peux venir à la boutique", "INFO_GENERAL", 2),
    ("Vous avez un point de vente", "INFO_GENERAL", 2),
    ("C'est quelle commune", "INFO_GENERAL", 2),
    ("Vous êtes ouvert jusqu'à quelle heure", "INFO_GENERAL", 2),
    ("Quels sont vos horaires", "INFO_GENERAL", 2),
    ("Vous travaillez le dimanche", "INFO_GENERAL", 2),
    ("Vous êtes en ligne seulement", "INFO_GENERAL", 2),

    # PRICE
    ("C'est combien", "PRICE", 6),
    ("Quel est le prix", "PRICE", 6),
    ("Combien le paquet", "PRICE", 6),
    ("C'est combien dans le paquet", "PRICE", 6),
    ("Y'a combien dedans", "PRICE", 6),
    ("Le prix s'il vous plaît", "PRICE", 6),
    ("Pouvez-vous vérifier le prix", "PRICE", 6),
    ("Quel est le tarif", "PRICE", 6),
    ("C'est à combien", "PRICE", 6),
    ("Prix en gros", "PRICE", 6),
    ("Le prix de gros c'est combien", "PRICE", 6),
    ("Combien pour 10 paquets", "PRICE", 6),
    ("Vous avez des promotions", "PRICE", 6),
    ("Y'a des réductions", "PRICE", 6),
    ("Le prix a changé ou pas", "PRICE", 6),

    # PRODUCT_INFO
    ("Vous avez quoi comme produits", "PRODUCT_INFO", 4),
    ("Pouvez-vous m'en dire plus", "PRODUCT_INFO", 4),
    ("J'aimerais voir vos produits", "PRODUCT_INFO", 4),
    ("Qu'est-ce que vous vendez", "PRODUCT_INFO", 4),
    ("Vous avez un catalogue", "PRODUCT_INFO", 4),
    ("Montrez-moi ce que vous avez", "PRODUCT_INFO", 4),
    ("Dites-moi vos articles", "PRODUCT_INFO", 4),
    ("Quels sont vos produits disponibles", "PRODUCT_INFO", 4),
    ("Vous vendez quoi exactement", "PRODUCT_INFO", 4),
    ("Présentez-moi vos articles", "PRODUCT_INFO", 4),
    ("J'aimerais connaître vos produits", "PRODUCT_INFO", 4),
    ("Vous avez quoi en stock", "STOCK", 7),

    # PRODUCT_INFO
    ("Vous avez des couches taille 4", "PRODUCT_INFO", 5),
    ("Les couches à pression sont disponibles", "PRODUCT_INFO", 5),
    ("Vous avez la marque Pampers", "PRODUCT_INFO", 5),
    ("C'est quelle taille ça", "PRODUCT_INFO", 5),
    ("Les couches nouveau-né vous avez", "PRODUCT_INFO", 5),
    ("Vous avez des couches adultes", "PRODUCT_INFO", 5),
    ("Y'a des couches culottes", "PRODUCT_INFO", 5),
    ("Vous vendez quelle marque", "PRODUCT_INFO", 5),
    ("Les tailles disponibles", "PRODUCT_INFO", 5),
    ("Vous avez en stock actuellement", "STOCK", 7),
    ("C'est pour quel âge ces couches", "PRODUCT_INFO", 5),
    ("Différence entre les modèles", "PRODUCT_INFO", 5),

    # ORDER_CREATE
    ("Je veux commander", "ORDER_CREATE", 8),
    ("Je prends 5 paquets", "ORDER_CREATE", 8),
    ("Comment passer commande", "ORDER_CREATE", 8),
    ("Je veux acheter", "ORDER_CREATE", 8),
    ("Envoie-moi 10 paquets", "ORDER_CREATE", 8),
    ("Je commande maintenant", "ORDER_CREATE", 8),
    ("Comment faire pour acheter", "ORDER_CREATE", 8),
    ("Je vais prendre ça", "ORDER_CREATE", 8),
    ("J'en veux 3 paquets", "ORDER_CREATE", 8),
    ("Je passe commande", "ORDER_CREATE", 8),
    ("Réserve-moi 2 cartons", "ORDER_CREATE", 8),
    ("Je reviens pour commander", "ORDER_CREATE", 8),

    # DELIVERY_INFO
    ("Vous livrez à Yopougon", "DELIVERY_INFO", 9),
    ("Comment se passe la livraison", "DELIVERY_INFO", 9),
    ("La livraison c'est combien", "DELIVERY_INFO", 9),
    ("Vous livrez quand", "DELIVERY_INFO", 9),
    ("Je veux être livré demain", "DELIVERY_INFO", 9),
    ("Livraison à Cocody possible", "DELIVERY_INFO", 9),
    ("Les frais de livraison", "DELIVERY_INFO", 9),
    ("Vous pouvez livrer ce soir", "DELIVERY_INFO", 9),
    ("La livraison prend combien de temps", "DELIVERY_INFO", 9),
    ("Je veux changer l'adresse de livraison", "DELIVERY_MODIFY", 11),

    # PAYMENT
    ("Vous acceptez quoi comme paiement", "PAYMENT", 10),
    ("Je peux payer avec Wave", "PAYMENT", 10),
    ("Mode de paiement disponible", "PAYMENT", 10),
    ("Vous prenez Orange Money", "PAYMENT", 10),
    ("Paiement à la livraison possible", "PAYMENT", 10),
    ("Je paie comment", "PAYMENT", 10),
    ("MTN Money ça passe", "PAYMENT", 10),
    ("Vous acceptez les espèces", "PAYMENT", 10),

    # CONTACT_COORDONNEES
    ("Quel est votre numéro", "CONTACT_COORDONNEES", 13),
    ("Je peux vous appeler", "CONTACT_COORDONNEES", 13),
    ("Donnez-moi votre contact", "CONTACT_COORDONNEES", 13),
    ("Comment vous contacter", "CONTACT_COORDONNEES", 13),
    ("Votre WhatsApp", "CONTACT_COORDONNEES", 13),
    ("Je vous appelle mais pas de réponse", "CONTACT_COORDONNEES", 13),
    ("C'est quel numéro pour vous joindre", "CONTACT_COORDONNEES", 13),
    ("Vos coordonnées s'il vous plaît", "CONTACT_COORDONNEES", 13),

    # ORDER_MODIFY
    ("Le paquet est abîmé", "PROBLEME", 12),
    ("Les couches ne sont pas bonnes", "PROBLEME", 12),
    ("Je n'ai pas reçu ma commande", "PROBLEME", 12),
    ("Il y a un problème avec le colis", "PROBLEME", 12),
    ("Je veux retourner le produit", "PROBLEME", 12),

    # TRACKING
    ("Où est ma commande", "TRACKING", 11),
    ("Mon colis arrive quand", "TRACKING", 11),
    ("Le livreur est parti", "TRACKING", 11),
    ("Je n'ai pas encore reçu", "TRACKING", 11),
    ("Suivi de ma commande", "TRACKING", 11),
    ("C'est à quel niveau mon colis", "TRACKING", 11),
    ("Le livreur ne répond pas", "TRACKING", 11),
    ("Ma commande a été expédiée", "TRACKING", 11),

    # STOCK
    ("Vous avez en stock actuellement", "STOCK", 7),
    ("Vous avez quoi en stock", "STOCK", 7),
    ("Vous avez en stock", "STOCK", 7),
    ("C'est disponible maintenant", "STOCK", 7),
    ("C'est en rupture ou pas", "STOCK", 7),
    ("Il en reste combien", "STOCK", 7),
    ("Quand ça revient en stock", "STOCK", 7),
    ("Vous n'avez plus ce modèle", "STOCK", 7),
    ("C'est dispo pour aujourd'hui", "STOCK", 7),
    ("Vous avez le produit X en stock", "STOCK", 7),
]
